export const path = {
  home: '/',
  signup: '/signup',
  login: '/login',
  profile: '/profile',
  lockScreen: '/lock-screen',
  logout: '/logout',
  taskManager: '/task-manager',
  test: '/test',
  timekeeping: '/timekeeping',
  chat: '/chat',
  logout: '/logout',
  project: '/project/:projectId',
  userManagement: '/user-management',
  socialNetwork: '/social-network',
};
